### ISSUE TITLE
ヒアリング

### ISSUE THREAD

**Issue by yutatanamoto** [yutatanamoto/winnerlights-ios-mobile-client#8]
2020/11/06にFC GOISにヒアリングすることになりました
アプリ開発チームから聞きたいことなどあればここでまとめておきましょう!

**Comment by yutatanamoto** [comment]
,m

**Comment by okappi0258** [comment]
聞いておくべきこと
・アプリ画面のボタンや文字のレイアウト、色、大きさなどは自分たちのデザインでいいのか
・最低限の機能はどこまでできるようにしたらいいのか
・シャツなどに取り付けるLEDの色は何色がいいのか

**Comment by shnsk35** [comment]
・exerlightsの改善点、特にアプリの使いづらかったこと
・あったらいいなと感じる機能：詳細画面、実行画面などで具体的に聞く

**Comment by yutatanamoto** [comment]
**当日必要なもの**
- [ ] カメラ
- [ ] 三脚
- [ ] 開発中のアプリ
　　 \* 実機で動かせるように
　　- [ ] iphone
- [ ] UIデザイン案
- [ ]

**Comment by yutatanamoto** [comment]
**確認すること**
-
